/* tools/gen_highways_data.py が生成。直接編集しない。
   仕様書ページ用の軽い一覧（経路の座標は含まない）。 */
const SPEC_ROUTES = [
  { num: 1, start: "東京", end: "大阪", prefs: ["東京都", "神奈川県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府"], diff: 3, len: 553, auto: false },
  { num: 2, start: "大阪", end: "北九州(門司)", prefs: ["大阪府", "兵庫県", "岡山県", "広島県", "山口県", "福岡県"], diff: 3, len: 528, auto: false },
  { num: 3, start: "北九州(門司)", end: "鹿児島", prefs: ["福岡県", "佐賀県", "熊本県", "鹿児島県"], diff: 3, len: 389, auto: false },
  { num: 4, start: "東京", end: "青森", prefs: ["東京都", "埼玉県", "茨城県", "栃木県", "福島県", "宮城県", "岩手県", "青森県"], diff: 3, len: 753, auto: false },
  { num: 5, start: "函館", end: "札幌", prefs: ["北海道"], diff: 3, len: 282, auto: false },
  { num: 6, start: "東京", end: "仙台", prefs: ["東京都", "千葉県", "茨城県", "福島県", "宮城県"], diff: 3, len: 347, auto: false },
  { num: 7, start: "新潟", end: "青森", prefs: ["新潟県", "山形県", "秋田県", "青森県"], diff: 3, len: 470, auto: false },
  { num: 8, start: "新潟", end: "京都", prefs: ["新潟県", "富山県", "石川県", "福井県", "滋賀県", "京都府"], diff: 3, len: 576, auto: false },
  { num: 9, start: "京都", end: "下関", prefs: ["京都府", "兵庫県", "鳥取県", "島根県", "山口県"], diff: 3, len: 634, auto: false },
  { num: 10, start: "北九州(小倉)", end: "鹿児島", prefs: ["福岡県", "大分県", "宮崎県", "鹿児島県"], diff: 3, len: 446, auto: false },
  { num: 11, start: "徳島", end: "松山", prefs: ["徳島県", "香川県", "愛媛県"], diff: 3, len: 230, auto: false },
  { num: 12, start: "札幌", end: "旭川", prefs: ["北海道"], diff: 3, len: 136, auto: false },
  { num: 13, start: "福島", end: "秋田", prefs: ["福島県", "山形県", "秋田県"], diff: 3, len: 301, auto: false },
  { num: 14, start: "東京(日本橋)", end: "千葉", prefs: ["東京都", "千葉県"], diff: 3, len: 38, auto: false },
  { num: 15, start: "東京(日本橋)", end: "横浜", prefs: ["東京都", "神奈川県"], diff: 3, len: 28, auto: false },
  { num: 16, start: "横浜", end: "横浜(一周)", prefs: ["神奈川県", "東京都", "埼玉県", "千葉県"], diff: 3, len: 265, auto: false },
  { num: 17, start: "東京", end: "新潟", prefs: ["東京都", "埼玉県", "群馬県", "新潟県"], diff: 3, len: 350, auto: false },
  { num: 18, start: "高崎", end: "上越", prefs: ["群馬県", "長野県", "新潟県"], diff: 3, len: 191, auto: false },
  { num: 19, start: "名古屋", end: "長野", prefs: ["愛知県", "岐阜県", "長野県"], diff: 3, len: 255, auto: false },
  { num: 20, start: "東京", end: "塩尻", prefs: ["東京都", "神奈川県", "山梨県", "長野県"], diff: 3, len: 216, auto: false },
  { num: 21, start: "瑞浪", end: "米原", prefs: ["岐阜県", "滋賀県"], diff: 3, len: 100, auto: false },
  { num: 22, start: "名古屋", end: "岐阜", prefs: ["愛知県", "岐阜県"], diff: 3, len: 26, auto: false },
  { num: 23, start: "豊橋", end: "伊勢", prefs: ["愛知県", "三重県"], diff: 3, len: 168, auto: false },
  { num: 24, start: "京都", end: "和歌山", prefs: ["京都府", "奈良県", "和歌山県"], diff: 3, len: 136, auto: false },
  { num: 25, start: "四日市", end: "大阪", prefs: ["三重県", "奈良県", "大阪府"], diff: 3, len: 149, auto: false },
  { num: 26, start: "大阪", end: "和歌山", prefs: ["大阪府", "和歌山県"], diff: 3, len: 70, auto: false },
  { num: 27, start: "敦賀", end: "京丹波", prefs: ["福井県", "京都府"], diff: 3, len: 134, auto: false },
  { num: 28, start: "神戸", end: "徳島", prefs: ["兵庫県", "徳島県"], diff: 3, len: 105, auto: false },
  { num: 29, start: "姫路", end: "鳥取", prefs: ["兵庫県", "鳥取県"], diff: 3, len: 108, auto: false },
  { num: 30, start: "岡山", end: "高松", prefs: ["岡山県", "香川県"], diff: 3, len: 43, auto: false },
  { num: 31, start: "海田", end: "呉", prefs: ["広島県"], diff: 3, len: 19, auto: false },
  { num: 32, start: "高松", end: "高知", prefs: ["香川県", "徳島県", "高知県"], diff: 3, len: 136, auto: false },
  { num: 33, start: "高知", end: "松山", prefs: ["高知県", "愛媛県"], diff: 3, len: 116, auto: false },
  { num: 34, start: "鳥栖", end: "長崎", prefs: ["佐賀県", "長崎県"], diff: 3, len: 132, auto: false },
  { num: 35, start: "佐世保", end: "武雄", prefs: ["長崎県", "佐賀県"], diff: 3, len: 35, auto: false },
  { num: 36, start: "札幌", end: "室蘭", prefs: ["北海道"], diff: 3, len: 133, auto: false },
  { num: 37, start: "長万部", end: "室蘭", prefs: ["北海道"], diff: 3, len: 77, auto: false },
  { num: 38, start: "滝川", end: "釧路", prefs: ["北海道"], diff: 3, len: 295, auto: false },
  { num: 39, start: "旭川", end: "網走", prefs: ["北海道"], diff: 3, len: 216, auto: false },
  { num: 40, start: "旭川", end: "稚内", prefs: ["北海道"], diff: 3, len: 250, auto: false },
  { num: 41, start: "名古屋", end: "富山", prefs: ["愛知県", "岐阜県", "富山県"], diff: 3, len: 239, auto: false },
  { num: 42, start: "和歌山", end: "松阪", prefs: ["和歌山県", "三重県"], diff: 3, len: 352, auto: false },
  { num: 43, start: "大阪", end: "神戸", prefs: ["大阪府", "兵庫県"], diff: 3, len: 26, auto: false },
  { num: 44, start: "釧路", end: "根室", prefs: ["北海道"], diff: 3, len: 121, auto: false },
  { num: 45, start: "仙台", end: "青森", prefs: ["宮城県", "岩手県", "青森県"], diff: 3, len: 506, auto: false },
  { num: 46, start: "盛岡", end: "秋田", prefs: ["岩手県", "秋田県"], diff: 3, len: 116, auto: false },
  { num: 47, start: "仙台", end: "酒田", prefs: ["宮城県", "山形県"], diff: 3, len: 169, auto: false },
  { num: 48, start: "仙台", end: "山形", prefs: ["宮城県", "山形県"], diff: 3, len: 68, auto: false },
  { num: 49, start: "いわき", end: "新潟", prefs: ["福島県", "新潟県"], diff: 3, len: 234, auto: false },
  { num: 50, start: "前橋", end: "水戸", prefs: ["群馬県", "栃木県", "茨城県"], diff: 3, len: 144, auto: false },
  { num: 51, start: "千葉", end: "水戸", prefs: ["千葉県", "茨城県"], diff: 3, len: 124, auto: false },
  { num: 52, start: "静岡(清水)", end: "甲斐", prefs: ["静岡県", "山梨県"], diff: 3, len: 89, auto: false },
  { num: 53, start: "岡山", end: "鳥取", prefs: ["岡山県", "鳥取県"], diff: 3, len: 135, auto: false },
  { num: 54, start: "広島", end: "松江", prefs: ["広島県", "島根県"], diff: 3, len: 166, auto: false },
  { num: 55, start: "徳島", end: "高知", prefs: ["徳島県", "高知県"], diff: 3, len: 205, auto: false },
  { num: 56, start: "高知", end: "松山", prefs: ["高知県", "愛媛県"], diff: 3, len: 293, auto: false },
  { num: 57, start: "大分", end: "長崎", prefs: ["大分県", "熊本県", "長崎県"], diff: 3, len: 275, auto: false },
  { num: 58, start: "鹿児島", end: "那覇", prefs: ["鹿児島県", "沖縄県"], diff: 3, len: 800, auto: false },
  { num: 101, start: "青森", end: "秋田", prefs: ["青森県", "秋田県"], diff: 3, len: 241, auto: true },
  { num: 102, start: "弘前", end: "十和田", prefs: ["青森県"], diff: 3, len: 103, auto: true },
  { num: 103, start: "青森", end: "大館", prefs: ["青森県", "秋田県"], diff: 3, len: 130, auto: true },
  { num: 104, start: "八戸", end: "大館", prefs: ["青森県", "秋田県"], diff: 3, len: 123, auto: true },
  { num: 105, start: "由利本荘", end: "北秋田", prefs: ["秋田県"], diff: 3, len: 170, auto: true },
  { num: 106, start: "宮古", end: "盛岡", prefs: ["岩手県"], diff: 3, len: 90, auto: true },
  { num: 107, start: "大船渡", end: "由利本荘", prefs: ["岩手県", "秋田県"], diff: 3, len: 192, auto: true },
  { num: 108, start: "石巻", end: "由利本荘", prefs: ["宮城県", "秋田県"], diff: 3, len: 184, auto: true },
  { num: 112, start: "山形", end: "酒田", prefs: ["山形県"], diff: 3, len: 144, auto: true },
  { num: 113, start: "新潟", end: "相馬", prefs: ["新潟県", "福島県"], diff: 3, len: 229, auto: true },
  { num: 114, start: "福島", end: "浪江", prefs: ["福島県"], diff: 3, len: 68, auto: true },
  { num: 115, start: "相馬", end: "猪苗代", prefs: ["福島県"], diff: 3, len: 109, auto: true },
  { num: 116, start: "柏崎", end: "新潟", prefs: ["新潟県"], diff: 3, len: 86, auto: true },
  { num: 117, start: "長野", end: "小千谷", prefs: ["長野県", "新潟県"], diff: 3, len: 123, auto: true },
  { num: 118, start: "水戸", end: "会津若松", prefs: ["茨城県", "福島県"], diff: 3, len: 196, auto: true },
  { num: 119, start: "日光", end: "宇都宮", prefs: ["栃木県"], diff: 3, len: 39, auto: true },
  { num: 120, start: "日光", end: "沼田", prefs: ["栃木県", "群馬県"], diff: 3, len: 87, auto: true },
  { num: 121, start: "米沢", end: "益子", prefs: ["山形県", "栃木県"], diff: 3, len: 247, auto: true },
  { num: 122, start: "日光", end: "豊島", prefs: ["栃木県", "東京都"], diff: 3, len: 158, auto: true },
  { num: 123, start: "宇都宮", end: "水戸", prefs: ["栃木県", "茨城県"], diff: 3, len: 69, auto: true },
  { num: 124, start: "銚子", end: "水戸", prefs: ["千葉県", "茨城県"], diff: 3, len: 87, auto: true },
  { num: 125, start: "香取", end: "熊谷", prefs: ["千葉県", "埼玉県"], diff: 3, len: 131, auto: true },
  { num: 126, start: "銚子", end: "千葉", prefs: ["千葉県"], diff: 3, len: 82, auto: true },
  { num: 127, start: "館山", end: "木更津", prefs: ["千葉県"], diff: 3, len: 55, auto: true },
  { num: 128, start: "館山", end: "千葉", prefs: ["千葉県"], diff: 3, len: 132, auto: true },
  { num: 129, start: "平塚", end: "相模原", prefs: ["神奈川県"], diff: 3, len: 61, auto: true },
  { num: 130, start: "港", end: "港", prefs: ["東京都"], diff: 3, len: 1, auto: true, excluded: "短すぎる(0.7km)" },
  { num: 131, start: "大田", end: "大田", prefs: ["東京都"], diff: 3, len: 4, auto: true, excluded: "短すぎる(4.3km)" },
  { num: 132, start: "川崎", end: "川崎", prefs: ["神奈川県"], diff: 3, len: 8, auto: true, excluded: "短すぎる(8.1km)" },
  { num: 133, start: "横浜", end: "横浜", prefs: ["神奈川県"], diff: 3, len: 1, auto: true, excluded: "短すぎる(1.4km)" },
  { num: 134, start: "横須賀", end: "大磯", prefs: ["神奈川県"], diff: 3, len: 42, auto: false },
  { num: 135, start: "熱海", end: "下田", prefs: ["静岡県"], diff: 3, len: 73, auto: false },
  { num: 136, start: "下田", end: "三島", prefs: ["静岡県"], diff: 3, len: 110, auto: true },
  { num: 137, start: "富士吉田", end: "笛吹", prefs: ["山梨県"], diff: 3, len: 32, auto: true },
  { num: 138, start: "富士吉田", end: "小田原", prefs: ["山梨県", "神奈川県"], diff: 3, len: 60, auto: true },
  { num: 139, start: "富士", end: "奥多摩", prefs: ["静岡県", "東京都"], diff: 3, len: 121, auto: true },
  { num: 140, start: "熊谷", end: "富士川", prefs: ["埼玉県", "山梨県"], diff: 3, len: 142, auto: true },
  { num: 141, start: "韮崎", end: "上田", prefs: ["山梨県", "長野県"], diff: 3, len: 105, auto: true },
  { num: 142, start: "軽井沢", end: "下諏訪", prefs: ["長野県"], diff: 3, len: 77, auto: true },
  { num: 143, start: "松本", end: "上田", prefs: ["長野県"], diff: 3, len: 52, auto: true },
  { num: 144, start: "長野原", end: "上田", prefs: ["群馬県", "長野県"], diff: 3, len: 44, auto: true },
  { num: 145, start: "長野原", end: "沼田", prefs: ["群馬県"], diff: 3, len: 48, auto: true },
  { num: 146, start: "長野原", end: "軽井沢", prefs: ["群馬県", "長野県"], diff: 3, len: 30, auto: true },
  { num: 147, start: "大", end: "松本", prefs: ["長野県"], diff: 3, len: 32, auto: true },
  { num: 148, start: "大", end: "糸魚川", prefs: ["長野県", "新潟県"], diff: 3, len: 70, auto: true },
  { num: 149, start: "静岡", end: "静岡", prefs: ["静岡県"], diff: 3, len: 3, auto: true, excluded: "短すぎる(2.8km)" },
  { num: 150, start: "静岡", end: "浜松", prefs: ["静岡県"], diff: 3, len: 101, auto: true },
  { num: 151, start: "飯田", end: "豊橋", prefs: ["長野県", "愛知県"], diff: 3, len: 131, auto: true },
  { num: 152, start: "上田", end: "浜松", prefs: ["長野県", "静岡県"], diff: 3, len: 246, auto: true },
  { num: 153, start: "名古屋", end: "塩尻", prefs: ["愛知県", "長野県"], diff: 3, len: 212, auto: true },
  { num: 154, start: "名古屋", end: "名古屋", prefs: ["愛知県"], diff: 3, len: 8, auto: true, excluded: "短すぎる(8.1km)" },
  { num: 155, start: "常滑", end: "弥富", prefs: ["愛知県"], diff: 3, len: 124, auto: true },
  { num: 156, start: "岐阜", end: "高岡", prefs: ["岐阜県", "富山県"], diff: 3, len: 212, auto: true },
  { num: 157, start: "金沢", end: "岐阜", prefs: ["石川県", "岐阜県"], diff: 3, len: 198, auto: true },
  { num: 158, start: "福井", end: "松本", prefs: ["福井県", "岐阜県", "長野県"], diff: 3, len: 250, auto: false },
  { num: 159, start: "七尾", end: "金沢", prefs: ["石川県"], diff: 3, len: 68, auto: true },
  { num: 160, start: "七尾", end: "高岡", prefs: ["石川県", "富山県"], diff: 3, len: 45, auto: true },
  { num: 161, start: "敦賀", end: "大津", prefs: ["福井県", "滋賀県"], diff: 3, len: 98, auto: true },
  { num: 162, start: "京都", end: "敦賀", prefs: ["京都府", "福井県"], diff: 3, len: 143, auto: true },
  { num: 163, start: "大阪", end: "津", prefs: ["大阪府", "三重県"], diff: 3, len: 113, auto: true },
  { num: 164, start: "四日", end: "四日", prefs: ["三重県"], diff: 3, len: 3, auto: true, excluded: "短すぎる(3.3km)" },
  { num: 165, start: "大阪", end: "津", prefs: ["大阪府", "三重県"], diff: 3, len: 126, auto: true },
  { num: 166, start: "羽曳野", end: "松阪", prefs: ["大阪府", "三重県"], diff: 3, len: 126, auto: true },
  { num: 167, start: "志摩", end: "伊勢", prefs: ["三重県"], diff: 3, len: 39, auto: true },
  { num: 168, start: "新宮", end: "枚方", prefs: ["和歌山県", "大阪府"], diff: 3, len: 186, auto: true },
  { num: 169, start: "奈良", end: "新宮", prefs: ["奈良県", "和歌山県"], diff: 3, len: 179, auto: true },
  { num: 170, start: "不明", end: "不明", prefs: [], diff: 3, len: 25, auto: true, excluded: "from/toタグが無い" },
  { num: 171, start: "京都", end: "神戸", prefs: ["京都府", "大阪府", "兵庫県"], diff: 3, len: 65, auto: false },
  { num: 172, start: "大阪", end: "大阪", prefs: ["大阪府"], diff: 3, len: 12, auto: true, excluded: "経路の点が少なすぎる(7点)" },
  { num: 173, start: "池田", end: "綾部", prefs: ["大阪府", "京都府"], diff: 3, len: 70, auto: true },
  { num: 174, start: "神戸", end: "神戸", prefs: ["兵庫県"], diff: 3, len: 0, auto: true, excluded: "短すぎる(0.2km)" },
  { num: 175, start: "不明", end: "不明", prefs: [], diff: 3, len: 125, auto: true, excluded: "from/toタグが無い" },
  { num: 176, start: "大阪", end: "舞鶴", prefs: ["大阪府", "兵庫県", "京都府"], diff: 3, len: 160, auto: false },
  { num: 177, start: "舞鶴", end: "舞鶴", prefs: ["京都府"], diff: 3, len: 1, auto: true, excluded: "短すぎる(0.7km)" },
  { num: 178, start: "舞鶴", end: "岩美", prefs: ["京都府", "鳥取県"], diff: 3, len: 177, auto: true },
  { num: 179, start: "姫路", end: "湯梨浜", prefs: ["兵庫県", "鳥取県"], diff: 3, len: 154, auto: true },
  { num: 180, start: "岡山", end: "松江", prefs: ["岡山県", "島根県"], diff: 3, len: 195, auto: true },
  { num: 181, start: "津山", end: "米子", prefs: ["岡山県", "鳥取県"], diff: 3, len: 99, auto: true },
  { num: 182, start: "新見", end: "福山", prefs: ["岡山県", "広島県"], diff: 3, len: 80, auto: true },
  { num: 183, start: "江津", end: "大竹", prefs: ["島根県", "広島県"], diff: 3, len: 191, auto: true },
  { num: 184, start: "出雲", end: "尾道", prefs: ["島根県", "広島県"], diff: 3, len: 166, auto: true },
  { num: 185, start: "呉", end: "三原", prefs: ["広島県"], diff: 3, len: 75, auto: true },
  { num: 186, start: "江津", end: "大竹", prefs: ["島根県", "広島県"], diff: 3, len: 154, auto: true },
  { num: 187, start: "岩国", end: "益田", prefs: ["山口県", "島根県"], diff: 3, len: 108, auto: true },
  { num: 188, start: "岩国", end: "下松", prefs: ["山口県"], diff: 3, len: 68, auto: true },
  { num: 189, start: "岩国", end: "岩国", prefs: ["山口県"], diff: 3, len: 3, auto: true, excluded: "短すぎる(2.9km)" },
  { num: 190, start: "山口", end: "山陽小野田", prefs: ["山口県"], diff: 3, len: 44, auto: true },
  { num: 191, start: "下関", end: "広島", prefs: ["山口県", "広島県"], diff: 3, len: 291, auto: true },
  { num: 192, start: "西条", end: "徳島", prefs: ["愛媛県", "徳島県"], diff: 3, len: 136, auto: true },
  { num: 193, start: "高松", end: "海陽", prefs: ["香川県", "徳島県"], diff: 3, len: 153, auto: true },
  { num: 194, start: "高知", end: "西条", prefs: ["高知県", "愛媛県"], diff: 3, len: 88, auto: true },
  { num: 195, start: "高知", end: "徳島", prefs: ["高知県", "徳島県"], diff: 3, len: 176, auto: true },
  { num: 196, start: "松山", end: "西条", prefs: ["愛媛県"], diff: 3, len: 66, auto: true },
  { num: 197, start: "高知", end: "大分", prefs: ["高知県", "大分県"], diff: 3, len: 253, auto: true },
  { num: 198, start: "北九州", end: "北九州", prefs: ["福岡県"], diff: 3, len: 1, auto: true, excluded: "短すぎる(0.6km)" },
  { num: 199, start: "北九州", end: "北九州", prefs: ["福岡県"], diff: 3, len: 32, auto: true },
  { num: 200, start: "北九州", end: "筑紫野", prefs: ["福岡県"], diff: 3, len: 60, auto: true },
  { num: 201, start: "福岡", end: "苅田", prefs: ["福岡県"], diff: 3, len: 66, auto: true },
  { num: 202, start: "福岡", end: "長崎", prefs: ["福岡県", "長崎県"], diff: 3, len: 196, auto: true },
  { num: 203, start: "唐津", end: "佐賀", prefs: ["佐賀県"], diff: 3, len: 43, auto: true },
  { num: 204, start: "唐津", end: "佐世保", prefs: ["佐賀県", "長崎県"], diff: 3, len: 156, auto: true },
  { num: 205, start: "佐世保", end: "東彼杵", prefs: ["長崎県"], diff: 3, len: 23, auto: true },
  { num: 206, start: "長崎", end: "佐世保", prefs: ["長崎県"], diff: 3, len: 48, auto: true },
  { num: 207, start: "佐賀", end: "時津", prefs: ["佐賀県", "長崎県"], diff: 3, len: 108, auto: true },
  { num: 208, start: "熊本", end: "佐賀", prefs: ["熊本県", "佐賀県"], diff: 3, len: 85, auto: true },
  { num: 209, start: "大牟田", end: "久留米", prefs: ["福岡県"], diff: 3, len: 36, auto: true },
  { num: 210, start: "久留米", end: "大分", prefs: ["福岡県", "大分県"], diff: 3, len: 133, auto: true },
  { num: 211, start: "日田", end: "北九州", prefs: ["大分県", "福岡県"], diff: 3, len: 76, auto: true },
  { num: 212, start: "中津", end: "阿蘇", prefs: ["大分県", "熊本県"], diff: 3, len: 110, auto: true },
  { num: 213, start: "別府", end: "中津", prefs: ["大分県"], diff: 3, len: 126, auto: true },
  { num: 217, start: "大分", end: "佐伯", prefs: ["大分県"], diff: 3, len: 92, auto: true },
  { num: 218, start: "熊本", end: "延岡", prefs: ["熊本県", "宮崎県"], diff: 3, len: 144, auto: true },
  { num: 219, start: "熊本", end: "宮崎", prefs: ["熊本県", "宮崎県"], diff: 3, len: 200, auto: true },
  { num: 220, start: "宮崎", end: "霧島", prefs: ["宮崎県", "鹿児島県"], diff: 3, len: 182, auto: true },
  { num: 221, start: "人吉", end: "都城", prefs: ["熊本県", "宮崎県"], diff: 3, len: 74, auto: true },
  { num: 222, start: "日南", end: "都城", prefs: ["宮崎県"], diff: 3, len: 58, auto: true },
  { num: 223, start: "小林", end: "霧島", prefs: ["宮崎県", "鹿児島県"], diff: 3, len: 68, auto: true },
  { num: 224, start: "垂水", end: "鹿児島", prefs: ["鹿児島県"], diff: 3, len: 18, auto: true },
  { num: 225, start: "枕崎", end: "鹿児島", prefs: ["鹿児島県"], diff: 3, len: 52, auto: true },
  { num: 226, start: "南さつま", end: "鹿児島", prefs: ["鹿児島県"], diff: 3, len: 153, auto: true },
  { num: 227, start: "函館", end: "江差", prefs: ["北海道"], diff: 3, len: 70, auto: true },
  { num: 228, start: "函館", end: "江差", prefs: ["北海道"], diff: 3, len: 156, auto: true },
  { num: 229, start: "小樽", end: "江差", prefs: ["北海道"], diff: 3, len: 304, auto: true },
  { num: 230, start: "札幌", end: "せたな", prefs: ["北海道"], diff: 3, len: 200, auto: true },
  { num: 231, start: "札幌", end: "留萌", prefs: ["北海道"], diff: 3, len: 129, auto: true },
  { num: 232, start: "稚内", end: "留萌", prefs: ["北海道"], diff: 3, len: 186, auto: true },
  { num: 233, start: "旭川", end: "留萌", prefs: ["北海道"], diff: 3, len: 78, auto: true },
  { num: 234, start: "岩見沢", end: "苫小牧", prefs: ["北海道"], diff: 3, len: 70, auto: true },
  { num: 235, start: "室蘭", end: "浦河", prefs: ["北海道"], diff: 3, len: 195, auto: true },
  { num: 236, start: "帯広", end: "浦河", prefs: ["北海道"], diff: 3, len: 139, auto: true },
  { num: 237, start: "旭川", end: "浦河", prefs: ["北海道"], diff: 3, len: 260, auto: true },
  { num: 238, start: "網走", end: "稚内", prefs: ["北海道"], diff: 3, len: 319, auto: true },
  { num: 239, start: "網走", end: "留萌", prefs: ["北海道"], diff: 3, len: 294, auto: true },
  { num: 240, start: "釧路", end: "網走", prefs: ["北海道"], diff: 3, len: 149, auto: true },
  { num: 241, start: "弟子屈", end: "帯広", prefs: ["北海道"], diff: 3, len: 159, auto: true },
  { num: 242, start: "網走", end: "帯広", prefs: ["北海道"], diff: 3, len: 283, auto: true },
  { num: 243, start: "網走", end: "根室", prefs: ["北海道"], diff: 3, len: 173, auto: true },
  { num: 244, start: "網走", end: "根室", prefs: ["北海道"], diff: 3, len: 153, auto: true },
  { num: 245, start: "水戸", end: "日立", prefs: ["茨城県"], diff: 3, len: 42, auto: true },
  { num: 246, start: "東京(三宅坂)", end: "沼津", prefs: ["東京都", "神奈川県", "静岡県"], diff: 3, len: 123, auto: false },
  { num: 247, start: "名古屋", end: "豊橋", prefs: ["愛知県"], diff: 3, len: 152, auto: true },
  { num: 248, start: "市", end: "岐阜", prefs: ["愛知県", "岐阜県"], diff: 3, len: 115, auto: true },
  { num: 249, start: "七尾", end: "金沢", prefs: ["石川県"], diff: 3, len: 177, auto: true },
  { num: 250, start: "神戸", end: "岡山", prefs: ["兵庫県", "岡山県"], diff: 3, len: 144, auto: true },
  { num: 251, start: "長崎", end: "諫早", prefs: ["長崎県"], diff: 3, len: 143, auto: true },
  { num: 252, start: "柏崎", end: "会津若松", prefs: ["新潟県", "福島県"], diff: 3, len: 199, auto: true },
  { num: 253, start: "上越", end: "南魚沼", prefs: ["新潟県"], diff: 3, len: 68, auto: true },
  { num: 254, start: "文京", end: "松本", prefs: ["東京都", "長野県"], diff: 3, len: 226, auto: true },
  { num: 255, start: "秦野", end: "小田原", prefs: ["神奈川県"], diff: 3, len: 20, auto: true },
  { num: 256, start: "岐阜", end: "飯田", prefs: ["岐阜県", "長野県"], diff: 3, len: 255, auto: true },
  { num: 257, start: "浜松", end: "高山", prefs: ["静岡県", "岐阜県"], diff: 3, len: 238, auto: true },
  { num: 258, start: "大垣", end: "桑名", prefs: ["岐阜県", "三重県"], diff: 3, len: 49, auto: true },
  { num: 259, start: "不明", end: "不明", prefs: [], diff: 3, len: 66, auto: true, excluded: "from/toタグが無い" },
  { num: 260, start: "不明", end: "不明", prefs: [], diff: 3, len: 98, auto: true, excluded: "from/toタグが無い" },
  { num: 261, start: "広島", end: "江津", prefs: ["広島県", "島根県"], diff: 3, len: 114, auto: true },
  { num: 262, start: "萩", end: "防府", prefs: ["山口県"], diff: 3, len: 57, auto: true },
  { num: 263, start: "福岡", end: "佐賀", prefs: ["福岡県", "佐賀県"], diff: 3, len: 46, auto: true },
  { num: 264, start: "佐賀", end: "久留米", prefs: ["佐賀県", "福岡県"], diff: 3, len: 26, auto: true },
  { num: 265, start: "小林", end: "阿蘇", prefs: ["宮崎県", "熊本県"], diff: 3, len: 197, auto: true },
  { num: 266, start: "天草", end: "熊本", prefs: ["熊本県"], diff: 3, len: 156, auto: true },
  { num: 267, start: "人吉", end: "薩摩川内", prefs: ["熊本県", "鹿児島県"], diff: 3, len: 78, auto: true },
  { num: 268, start: "水俣", end: "宮崎", prefs: ["熊本県", "宮崎県"], diff: 3, len: 114, auto: true },
  { num: 269, start: "指宿", end: "宮崎", prefs: ["鹿児島県", "宮崎県"], diff: 3, len: 165, auto: true },
  { num: 270, start: "枕崎", end: "いちき串木野", prefs: ["鹿児島県"], diff: 3, len: 55, auto: true },
  { num: 271, start: "小田原", end: "厚木", prefs: ["神奈川県"], diff: 3, len: 45, auto: true },
  { num: 272, start: "釧路", end: "標津", prefs: ["北海道"], diff: 3, len: 112, auto: true },
  { num: 273, start: "帯広", end: "紋別", prefs: ["北海道"], diff: 3, len: 234, auto: true },
  { num: 274, start: "札幌", end: "標茶", prefs: ["北海道"], diff: 3, len: 391, auto: true },
  { num: 275, start: "札幌", end: "浜頓別", prefs: ["北海道"], diff: 3, len: 318, auto: true },
  { num: 276, start: "江差", end: "苫小牧", prefs: ["北海道"], diff: 3, len: 314, auto: true },
  { num: 277, start: "江差", end: "八雲", prefs: ["北海道"], diff: 3, len: 61, auto: true },
  { num: 278, start: "函館", end: "森", prefs: ["北海道"], diff: 3, len: 114, auto: true },
  { num: 279, start: "函館", end: "野辺地", prefs: ["北海道", "青森県"], diff: 3, len: 146, auto: true },
  { num: 280, start: "青森", end: "函館", prefs: ["青森県", "北海道"], diff: 3, len: 172, auto: true },
  { num: 281, start: "盛岡", end: "久慈", prefs: ["岩手県"], diff: 3, len: 111, auto: true },
  { num: 282, start: "盛岡", end: "平川", prefs: ["岩手県", "青森県"], diff: 3, len: 124, auto: true },
  { num: 283, start: "釜石", end: "花巻", prefs: ["岩手県"], diff: 3, len: 86, auto: true },
  { num: 284, start: "陸前高田", end: "一関", prefs: ["岩手県"], diff: 3, len: 66, auto: true },
  { num: 285, start: "秋田", end: "鹿角", prefs: ["秋田県"], diff: 3, len: 112, auto: true },
  { num: 286, start: "仙台", end: "山形", prefs: ["宮城県", "山形県"], diff: 3, len: 68, auto: true },
  { num: 287, start: "米沢", end: "東根", prefs: ["山形県"], diff: 3, len: 79, auto: true },
  { num: 288, start: "郡山", end: "双葉", prefs: ["福島県"], diff: 3, len: 72, auto: true },
  { num: 289, start: "新潟", end: "いわき", prefs: ["新潟県", "福島県"], diff: 3, len: 292, auto: true },
  { num: 290, start: "村上", end: "魚沼", prefs: ["新潟県"], diff: 3, len: 163, auto: true },
  { num: 291, start: "前橋", end: "柏崎", prefs: ["群馬県", "新潟県"], diff: 3, len: 189, auto: true },
  { num: 292, start: "長野原", end: "妙高", prefs: ["群馬県", "新潟県"], diff: 3, len: 111, auto: true },
  { num: 293, start: "日立", end: "足利", prefs: ["茨城県", "栃木県"], diff: 3, len: 160, auto: true },
  { num: 294, start: "柏", end: "会津若松", prefs: ["千葉県", "福島県"], diff: 3, len: 246, auto: true },
  { num: 295, start: "成田", end: "成田", prefs: ["千葉県"], diff: 3, len: 11, auto: true },
  { num: 296, start: "匝瑳", end: "船橋", prefs: ["千葉県"], diff: 3, len: 58, auto: true },
  { num: 297, start: "館山", end: "市原", prefs: ["千葉県"], diff: 3, len: 107, auto: true },
  { num: 298, start: "和光", end: "市川", prefs: ["埼玉県", "千葉県"], diff: 3, len: 43, auto: true },
  { num: 299, start: "茅野", end: "入間", prefs: ["長野県", "埼玉県"], diff: 3, len: 186, auto: true },
  { num: 300, start: "富士吉田", end: "身延", prefs: ["山梨県"], diff: 3, len: 45, auto: true },
  { num: 301, start: "浜松", end: "豊田", prefs: ["静岡県", "愛知県"], diff: 3, len: 99, auto: true },
  { num: 302, start: "名古屋", end: "名古屋", prefs: ["愛知県"], diff: 3, len: 33, auto: true },
  { num: 303, start: "岐阜", end: "若狭", prefs: ["岐阜県", "福井県"], diff: 3, len: 122, auto: true },
  { num: 304, start: "金沢", end: "南砺", prefs: ["石川県", "富山県"], diff: 3, len: 50, auto: true },
  { num: 305, start: "金沢", end: "南越前", prefs: ["石川県", "福井県"], diff: 3, len: 143, auto: true },
  { num: 306, start: "津", end: "彦根", prefs: ["三重県", "滋賀県"], diff: 3, len: 87, auto: true },
  { num: 307, start: "彦根", end: "枚方", prefs: ["滋賀県", "大阪府"], diff: 3, len: 102, auto: true },
  { num: 308, start: "大阪", end: "奈良", prefs: ["大阪府", "奈良県"], diff: 3, len: 32, auto: true },
  { num: 309, start: "熊野", end: "大阪", prefs: ["三重県", "大阪府"], diff: 3, len: 142, auto: true },
  { num: 310, start: "堺", end: "五條", prefs: ["大阪府", "奈良県"], diff: 3, len: 40, auto: true },
  { num: 311, start: "尾鷲", end: "上富田", prefs: ["三重県", "和歌山県"], diff: 3, len: 146, auto: true },
  { num: 312, start: "宮津", end: "姫路", prefs: ["京都府", "兵庫県"], diff: 3, len: 151, auto: true },
  { num: 313, start: "福山", end: "北栄", prefs: ["広島県", "鳥取県"], diff: 3, len: 166, auto: true },
  { num: 314, start: "福山", end: "雲南", prefs: ["広島県", "島根県"], diff: 3, len: 140, auto: true },
  { num: 315, start: "周南", end: "萩", prefs: ["山口県"], diff: 3, len: 89, auto: true },
  { num: 316, start: "長門", end: "山陽小野田", prefs: ["山口県"], diff: 3, len: 41, auto: true },
  { num: 317, start: "松山", end: "尾道", prefs: ["愛媛県", "広島県"], diff: 3, len: 116, auto: true },
  { num: 318, start: "徳島", end: "東かがわ", prefs: ["徳島県", "香川県"], diff: 3, len: 44, auto: true },
  { num: 319, start: "坂出", end: "四国中央", prefs: ["香川県", "愛媛県"], diff: 3, len: 103, auto: true },
  { num: 320, start: "宿毛", end: "鬼北", prefs: ["高知県", "愛媛県"], diff: 3, len: 95, auto: true },
  { num: 321, start: "四万十", end: "宿毛", prefs: ["高知県"], diff: 3, len: 80, auto: true },
  { num: 322, start: "北九州", end: "久留米", prefs: ["福岡県"], diff: 3, len: 83, auto: true },
  { num: 323, start: "佐賀", end: "唐津", prefs: ["佐賀県"], diff: 3, len: 45, auto: true },
  { num: 324, start: "長崎", end: "宇城", prefs: ["長崎県", "熊本県"], diff: 3, len: 106, auto: true },
  { num: 325, start: "久留米", end: "高千穂", prefs: ["福岡県", "宮崎県"], diff: 3, len: 132, auto: true },
  { num: 326, start: "延岡", end: "豊後大野", prefs: ["宮崎県", "大分県"], diff: 3, len: 68, auto: true },
  { num: 327, start: "日向", end: "山都", prefs: ["宮崎県", "熊本県"], diff: 3, len: 93, auto: true },
  { num: 328, start: "鹿児島", end: "出水", prefs: ["鹿児島県"], diff: 3, len: 63, auto: true },
  { num: 329, start: "名護", end: "那覇", prefs: ["沖縄県"], diff: 3, len: 78, auto: true },
  { num: 330, start: "沖縄", end: "那覇", prefs: ["沖縄県"], diff: 3, len: 25, auto: true },
  { num: 331, start: "那覇", end: "大宜味", prefs: ["沖縄県"], diff: 3, len: 146, auto: true },
  { num: 332, start: "那覇", end: "那覇", prefs: ["沖縄県"], diff: 3, len: 5, auto: true, excluded: "短すぎる(5.3km)" },
  { num: 333, start: "旭川", end: "北見", prefs: ["北海道"], diff: 3, len: 170, auto: true },
  { num: 334, start: "羅臼", end: "美幌", prefs: ["北海道"], diff: 3, len: 121, auto: true },
  { num: 335, start: "羅臼", end: "標津", prefs: ["北海道"], diff: 3, len: 42, auto: true },
  { num: 336, start: "浦河", end: "釧路", prefs: ["北海道"], diff: 3, len: 234, auto: true },
  { num: 337, start: "千歳", end: "小樽", prefs: ["北海道"], diff: 3, len: 87, auto: true },
  { num: 338, start: "函館", end: "おいらせ", prefs: ["北海道", "青森県"], diff: 3, len: 254, auto: true },
  { num: 339, start: "弘前", end: "外ヶ浜", prefs: ["青森県"], diff: 3, len: 110, auto: true },
  { num: 340, start: "陸前高田", end: "八戸", prefs: ["岩手県", "青森県"], diff: 3, len: 244, auto: true },
  { num: 341, start: "鹿角", end: "由利本荘", prefs: ["秋田県"], diff: 3, len: 170, auto: true },
  { num: 342, start: "横手", end: "登米", prefs: ["秋田県", "宮城県"], diff: 3, len: 148, auto: true },
  { num: 343, start: "陸前高田", end: "奥州", prefs: ["岩手県"], diff: 3, len: 60, auto: true },
  { num: 344, start: "湯沢", end: "酒田", prefs: ["秋田県", "山形県"], diff: 3, len: 98, auto: true },
  { num: 345, start: "新潟", end: "遊佐", prefs: ["新潟県", "山形県"], diff: 3, len: 208, auto: true },
  { num: 346, start: "仙台", end: "気仙沼", prefs: ["宮城県"], diff: 3, len: 124, auto: true },
  { num: 347, start: "寒河江", end: "大崎", prefs: ["山形県", "宮城県"], diff: 3, len: 89, auto: true },
  { num: 348, start: "長井", end: "山形", prefs: ["山形県"], diff: 3, len: 47, auto: true },
  { num: 349, start: "水戸", end: "柴田", prefs: ["茨城県", "宮城県"], diff: 3, len: 252, auto: true },
  { num: 350, start: "新潟", end: "上越", prefs: ["新潟県"], diff: 3, len: 190, auto: true },
  { num: 351, start: "長岡", end: "小千谷", prefs: ["新潟県"], diff: 3, len: 45, auto: true },
  { num: 352, start: "柏崎", end: "上三川", prefs: ["新潟県", "栃木県"], diff: 3, len: 328, auto: true },
  { num: 353, start: "桐生", end: "柏崎", prefs: ["群馬県", "新潟県"], diff: 3, len: 199, auto: true },
  { num: 354, start: "高崎", end: "鉾田", prefs: ["群馬県", "茨城県"], diff: 3, len: 172, auto: true },
  { num: 355, start: "香取", end: "笠間", prefs: ["千葉県", "茨城県"], diff: 3, len: 72, auto: true },
  { num: 356, start: "銚子", end: "我孫子", prefs: ["千葉県"], diff: 3, len: 92, auto: true },
  { num: 357, start: "千葉", end: "横須賀", prefs: ["千葉県", "東京都", "神奈川県"], diff: 3, len: 88, auto: false },
  { num: 358, start: "富士河口湖", end: "甲府", prefs: ["山梨県"], diff: 3, len: 28, auto: true },
  { num: 359, start: "富山", end: "金沢", prefs: ["富山県", "石川県"], diff: 3, len: 58, auto: true },
  { num: 360, start: "富山", end: "小松", prefs: ["富山県", "石川県"], diff: 3, len: 141, auto: true },
  { num: 361, start: "高山", end: "伊那", prefs: ["岐阜県", "長野県"], diff: 3, len: 115, auto: true },
  { num: 362, start: "豊川", end: "静岡", prefs: ["愛知県", "静岡県"], diff: 3, len: 152, auto: true },
  { num: 363, start: "名古屋", end: "中津川", prefs: ["愛知県", "岐阜県"], diff: 3, len: 78, auto: true },
  { num: 364, start: "大野", end: "加賀", prefs: ["福井県", "石川県"], diff: 3, len: 63, auto: true },
  { num: 365, start: "加賀", end: "四日", prefs: ["石川県", "三重県"], diff: 3, len: 225, auto: true },
  { num: 366, start: "半田", end: "名古屋", prefs: ["愛知県"], diff: 3, len: 18, auto: true },
  { num: 367, start: "京都", end: "若狭", prefs: ["京都府", "福井県"], diff: 3, len: 68, auto: true },
  { num: 368, start: "伊賀", end: "多気", prefs: ["三重県"], diff: 3, len: 73, auto: true },
  { num: 369, start: "奈良", end: "松阪", prefs: ["奈良県", "三重県"], diff: 3, len: 122, auto: true },
  { num: 370, start: "海南", end: "奈良", prefs: ["和歌山県", "奈良県"], diff: 3, len: 127, auto: true },
  { num: 371, start: "河内長野", end: "串本", prefs: ["大阪府", "和歌山県"], diff: 3, len: 213, auto: true },
  { num: 372, start: "亀岡", end: "姫路", prefs: ["京都府", "兵庫県"], diff: 3, len: 97, auto: true },
  { num: 373, start: "赤穂", end: "鳥取", prefs: ["兵庫県", "鳥取県"], diff: 3, len: 102, auto: true },
  { num: 374, start: "備前", end: "津山", prefs: ["岡山県"], diff: 3, len: 56, auto: true },
  { num: 375, start: "呉", end: "大田", prefs: ["広島県", "島根県"], diff: 3, len: 156, auto: true },
  { num: 376, start: "山口", end: "岩国", prefs: ["山口県"], diff: 3, len: 68, auto: true },
  { num: 377, start: "鳴門", end: "観音寺", prefs: ["徳島県", "香川県"], diff: 3, len: 120, auto: true },
  { num: 378, start: "伊予", end: "宇和島", prefs: ["愛媛県"], diff: 3, len: 121, auto: true },
  { num: 379, start: "松山", end: "内子", prefs: ["愛媛県"], diff: 3, len: 52, auto: true },
  { num: 380, start: "八幡浜", end: "久万高原", prefs: ["愛媛県"], diff: 3, len: 63, auto: true },
  { num: 381, start: "須崎", end: "宇和島", prefs: ["高知県", "愛媛県"], diff: 3, len: 112, auto: true },
  { num: 382, start: "対馬", end: "唐津", prefs: ["長崎県", "佐賀県"], diff: 3, len: 209, auto: true },
  { num: 383, start: "平戸", end: "伊万里", prefs: ["長崎県", "佐賀県"], diff: 3, len: 73, auto: true },
  { num: 384, start: "五島", end: "佐世保", prefs: ["長崎県"], diff: 3, len: 188, auto: true },
  { num: 385, start: "柳川", end: "福岡", prefs: ["福岡県"], diff: 3, len: 56, auto: true },
  { num: 386, start: "日田", end: "筑紫野", prefs: ["大分県", "福岡県"], diff: 3, len: 50, auto: true },
  { num: 387, start: "宇佐", end: "熊本", prefs: ["大分県", "熊本県"], diff: 3, len: 129, auto: true },
  { num: 388, start: "佐伯", end: "湯前", prefs: ["大分県", "熊本県"], diff: 3, len: 218, auto: true },
  { num: 389, start: "大牟田", end: "阿久根", prefs: ["福岡県", "鹿児島県"], diff: 3, len: 180, auto: true },
  { num: 390, start: "石垣", end: "那覇", prefs: ["沖縄県"], diff: 3, len: 474, auto: true },
  { num: 391, start: "釧路", end: "網走", prefs: ["北海道"], diff: 3, len: 152, auto: true },
  { num: 392, start: "釧路", end: "本別", prefs: ["北海道"], diff: 3, len: 83, auto: true },
  { num: 393, start: "小樽", end: "倶知安", prefs: ["北海道"], diff: 3, len: 58, auto: true },
  { num: 394, start: "むつ", end: "弘前", prefs: ["青森県"], diff: 3, len: 152, auto: true },
  { num: 395, start: "久慈", end: "二戸", prefs: ["岩手県"], diff: 3, len: 58, auto: true },
  { num: 396, start: "遠野", end: "盛岡", prefs: ["岩手県"], diff: 3, len: 58, auto: true },
  { num: 397, start: "大船渡", end: "横手", prefs: ["岩手県", "秋田県"], diff: 3, len: 135, auto: true },
  { num: 398, start: "石巻", end: "由利本荘", prefs: ["宮城県", "秋田県"], diff: 3, len: 269, auto: true },
  { num: 399, start: "いわき", end: "南陽", prefs: ["福島県", "山形県"], diff: 3, len: 190, auto: true },
  { num: 400, start: "水戸", end: "西会津", prefs: ["茨城県", "福島県"], diff: 3, len: 219, auto: true },
  { num: 401, start: "会津若松", end: "沼田", prefs: ["福島県", "群馬県"], diff: 3, len: 169, auto: true },
  { num: 402, start: "柏崎", end: "新潟", prefs: ["新潟県"], diff: 3, len: 87, auto: true },
  { num: 403, start: "新潟", end: "松本", prefs: ["新潟県", "長野県"], diff: 3, len: 327, auto: true },
  { num: 404, start: "長岡", end: "上越", prefs: ["新潟県"], diff: 3, len: 29, auto: true },
  { num: 405, start: "中之条", end: "上越", prefs: ["群馬県", "新潟県"], diff: 3, len: 120, auto: true },
  { num: 406, start: "大", end: "高崎", prefs: ["長野県", "群馬県"], diff: 3, len: 193, auto: true },
  { num: 407, start: "足利", end: "入間", prefs: ["栃木県", "埼玉県"], diff: 3, len: 59, auto: true },
  { num: 408, start: "成田", end: "高根沢", prefs: ["千葉県", "栃木県"], diff: 3, len: 118, auto: true },
  { num: 409, start: "川崎", end: "成田", prefs: ["神奈川県", "千葉県"], diff: 3, len: 119, auto: true },
  { num: 410, start: "館山", end: "木更津", prefs: ["千葉県"], diff: 3, len: 97, auto: true },
  { num: 411, start: "青梅", end: "甲府", prefs: ["東京都", "山梨県"], diff: 3, len: 101, auto: false },
  { num: 412, start: "平塚", end: "相模原", prefs: ["神奈川県"], diff: 3, len: 46, auto: true },
  { num: 413, start: "相模原", end: "富士吉田", prefs: ["神奈川県", "山梨県"], diff: 3, len: 70, auto: false },
  { num: 414, start: "下田", end: "沼津", prefs: ["静岡県"], diff: 3, len: 72, auto: true },
  { num: 415, start: "羽咋", end: "富山", prefs: ["石川県", "富山県"], diff: 3, len: 67, auto: true },
  { num: 416, start: "福井", end: "小松", prefs: ["福井県", "石川県"], diff: 3, len: 87, auto: true },
  { num: 417, start: "大垣", end: "南越前", prefs: ["岐阜県", "福井県"], diff: 3, len: 144, auto: true },
  { num: 418, start: "大野", end: "飯田", prefs: ["福井県", "長野県"], diff: 3, len: 252, auto: true },
  { num: 419, start: "瑞浪", end: "高浜", prefs: ["岐阜県", "愛知県"], diff: 3, len: 67, auto: true },
  { num: 420, start: "豊田", end: "新城", prefs: ["愛知県"], diff: 3, len: 67, auto: true },
  { num: 421, start: "桑名", end: "近江八幡", prefs: ["三重県", "滋賀県"], diff: 3, len: 62, auto: true },
  { num: 422, start: "大津", end: "紀北", prefs: ["滋賀県", "三重県"], diff: 3, len: 156, auto: true },
  { num: 423, start: "大阪", end: "亀岡", prefs: ["大阪府", "京都府"], diff: 3, len: 54, auto: true },
  { num: 424, start: "田辺", end: "紀の川", prefs: ["和歌山県"], diff: 3, len: 112, auto: true },
  { num: 425, start: "尾鷲", end: "御坊", prefs: ["三重県", "和歌山県"], diff: 3, len: 195, auto: true },
  { num: 426, start: "豊岡", end: "福知山", prefs: ["兵庫県", "京都府"], diff: 3, len: 47, auto: true },
  { num: 427, start: "明石", end: "朝来", prefs: ["兵庫県"], diff: 3, len: 98, auto: true },
  { num: 428, start: "神戸", end: "三木", prefs: ["兵庫県"], diff: 3, len: 30, auto: true },
  { num: 429, start: "倉敷", end: "福知山", prefs: ["岡山県", "京都府"], diff: 3, len: 248, auto: true },
  { num: 430, start: "倉敷", end: "玉野", prefs: ["岡山県"], diff: 3, len: 39, auto: true },
  { num: 431, start: "出雲", end: "米子", prefs: ["島根県", "鳥取県"], diff: 3, len: 93, auto: true },
  { num: 432, start: "竹原", end: "松江", prefs: ["広島県", "島根県"], diff: 3, len: 207, auto: true },
  { num: 433, start: "大竹", end: "三次", prefs: ["広島県"], diff: 3, len: 138, auto: true },
  { num: 434, start: "周南", end: "三次", prefs: ["山口県", "広島県"], diff: 3, len: 178, auto: true },
  { num: 435, start: "山口", end: "下関", prefs: ["山口県"], diff: 3, len: 71, auto: true },
  { num: 436, start: "姫路", end: "高松", prefs: ["兵庫県", "香川県"], diff: 3, len: 93, auto: true },
  { num: 437, start: "松山", end: "岩国", prefs: ["愛媛県", "山口県"], diff: 3, len: 112, auto: true },
  { num: 438, start: "徳島", end: "坂出", prefs: ["徳島県", "香川県"], diff: 3, len: 163, auto: true },
  { num: 439, start: "徳島", end: "四万十", prefs: ["徳島県", "高知県"], diff: 3, len: 334, auto: false },
  { num: 440, start: "松山", end: "檮原", prefs: ["愛媛県", "高知県"], diff: 3, len: 81, auto: true },
  { num: 441, start: "大洲", end: "四万十", prefs: ["愛媛県", "高知県"], diff: 3, len: 109, auto: true },
  { num: 442, start: "大分", end: "大川", prefs: ["大分県", "福岡県"], diff: 3, len: 162, auto: true },
  { num: 443, start: "大川", end: "氷川", prefs: ["福岡県", "熊本県"], diff: 3, len: 125, auto: true },
  { num: 444, start: "大", end: "佐賀", prefs: ["長崎県", "佐賀県"], diff: 3, len: 70, auto: true },
  { num: 445, start: "熊本", end: "人吉", prefs: ["熊本県"], diff: 3, len: 134, auto: true },
  { num: 446, start: "日向", end: "湯前", prefs: ["宮崎県", "熊本県"], diff: 3, len: 101, auto: true },
  { num: 447, start: "えびの", end: "出水", prefs: ["宮崎県", "鹿児島県"], diff: 3, len: 58, auto: true },
  { num: 448, start: "指宿", end: "宮崎", prefs: ["鹿児島県", "宮崎県"], diff: 3, len: 215, auto: true },
  { num: 449, start: "本部", end: "名護", prefs: ["沖縄県"], diff: 3, len: 18, auto: true },
  { num: 450, start: "旭川", end: "紋別", prefs: ["北海道"], diff: 3, len: 99, auto: true },
  { num: 451, start: "留萌", end: "滝川", prefs: ["北海道"], diff: 3, len: 120, auto: true },
  { num: 452, start: "夕張", end: "旭川", prefs: ["北海道"], diff: 3, len: 124, auto: true },
  { num: 453, start: "札幌", end: "伊達", prefs: ["北海道"], diff: 3, len: 123, auto: true },
  { num: 454, start: "八戸", end: "大鰐", prefs: ["青森県"], diff: 3, len: 114, auto: true },
  { num: 455, start: "盛岡", end: "岩泉", prefs: ["岩手県"], diff: 3, len: 99, auto: true },
  { num: 456, start: "盛岡", end: "気仙沼", prefs: ["岩手県", "宮城県"], diff: 3, len: 153, auto: true },
  { num: 457, start: "一関", end: "白石", prefs: ["岩手県", "宮城県"], diff: 3, len: 179, auto: true },
  { num: 458, start: "新庄", end: "上山", prefs: ["山形県"], diff: 3, len: 112, auto: true },
  { num: 459, start: "新潟", end: "浪江", prefs: ["新潟県", "福島県"], diff: 3, len: 260, auto: true },
  { num: 460, start: "新発田", end: "柏崎", prefs: ["新潟県"], diff: 3, len: 122, auto: true },
  { num: 461, start: "日光", end: "高萩", prefs: ["栃木県", "茨城県"], diff: 3, len: 134, auto: true },
  { num: 462, start: "佐久", end: "伊勢崎", prefs: ["長野県", "群馬県"], diff: 3, len: 117, auto: true },
  { num: 463, start: "越谷", end: "入間", prefs: ["埼玉県"], diff: 3, len: 42, auto: true },
  { num: 464, start: "松戸", end: "成田", prefs: ["千葉県"], diff: 3, len: 54, auto: true },
  { num: 465, start: "茂原", end: "富津", prefs: ["千葉県"], diff: 3, len: 109, auto: true },
  { num: 466, start: "世田谷", end: "横浜", prefs: ["東京都", "神奈川県"], diff: 3, len: 27, auto: true },
  { num: 467, start: "大和", end: "藤沢", prefs: ["神奈川県"], diff: 3, len: 21, auto: true },
  { num: 468, start: "横浜", end: "木更津", prefs: ["神奈川県", "千葉県"], diff: 3, len: 281, auto: true },
  { num: 469, start: "御殿場", end: "南部", prefs: ["静岡県", "山梨県"], diff: 3, len: 55, auto: true },
  { num: 470, start: "砺波", end: "輪島", prefs: ["富山県", "石川県"], diff: 3, len: 98, auto: true },
  { num: 471, start: "羽咋", end: "高山", prefs: ["石川県", "岐阜県"], diff: 3, len: 180, auto: true },
  { num: 472, start: "射水", end: "郡上", prefs: ["富山県", "岐阜県"], diff: 3, len: 184, auto: true },
  { num: 473, start: "市", end: "牧之原", prefs: ["愛知県", "静岡県"], diff: 3, len: 243, auto: true },
  { num: 474, start: "飯田", end: "浜松", prefs: ["長野県", "静岡県"], diff: 3, len: 105, auto: true },
  { num: 475, start: "豊田", end: "四日", prefs: ["愛知県", "三重県"], diff: 3, len: 154, auto: true },
  { num: 476, start: "大野", end: "敦賀", prefs: ["福井県"], diff: 3, len: 76, auto: true },
  { num: 477, start: "四日", end: "池田", prefs: ["三重県", "大阪府"], diff: 3, len: 222, auto: true },
  { num: 478, start: "宮津", end: "久御山", prefs: ["京都府"], diff: 3, len: 103, auto: true },
  { num: 479, start: "豊中", end: "大阪", prefs: ["大阪府"], diff: 3, len: 46, auto: true },
  { num: 480, start: "泉大津", end: "有田", prefs: ["大阪府", "和歌山県"], diff: 3, len: 130, auto: true },
  { num: 481, start: "泉佐野", end: "泉佐野", prefs: ["大阪府"], diff: 3, len: 22, auto: true },
  { num: 482, start: "宮津", end: "米子", prefs: ["京都府", "鳥取県"], diff: 3, len: 322, auto: true },
  { num: 483, start: "豊岡", end: "丹波", prefs: ["兵庫県"], diff: 3, len: 67, auto: true },
  { num: 484, start: "備前", end: "高梁", prefs: ["岡山県"], diff: 3, len: 92, auto: true },
  { num: 485, start: "隠岐の島", end: "松江", prefs: ["島根県"], diff: 3, len: 139, auto: true },
  { num: 486, start: "総社", end: "東広島", prefs: ["岡山県", "広島県"], diff: 3, len: 138, auto: true },
  { num: 487, start: "呉", end: "広島", prefs: ["広島県"], diff: 3, len: 63, auto: true },
  { num: 488, start: "益田", end: "廿日", prefs: ["島根県", "広島県"], diff: 3, len: 103, auto: true },
  { num: 489, start: "周南", end: "山口", prefs: ["山口県"], diff: 3, len: 44, auto: true },
  { num: 490, start: "宇部", end: "萩", prefs: ["山口県"], diff: 3, len: 60, auto: true },
  { num: 491, start: "下関", end: "長門", prefs: ["山口県"], diff: 3, len: 53, auto: true },
  { num: 492, start: "高松", end: "大豊", prefs: ["香川県", "高知県"], diff: 3, len: 169, auto: true },
  { num: 493, start: "高知", end: "東洋", prefs: ["高知県"], diff: 3, len: 95, auto: true },
  { num: 494, start: "松山", end: "須崎", prefs: ["愛媛県", "高知県"], diff: 3, len: 120, auto: true },
  { num: 495, start: "北九州", end: "福岡", prefs: ["福岡県"], diff: 3, len: 67, auto: true },
  { num: 496, start: "行橋", end: "日田", prefs: ["福岡県", "大分県"], diff: 3, len: 69, auto: true },
  { num: 498, start: "鹿島", end: "佐世保", prefs: ["佐賀県", "長崎県"], diff: 3, len: 60, auto: true },
  { num: 499, start: "長崎", end: "阿久根", prefs: ["長崎県", "鹿児島県"], diff: 3, len: 106, auto: true },
  { num: 500, start: "別府", end: "鳥栖", prefs: ["大分県", "佐賀県"], diff: 3, len: 158, auto: true },
  { num: 501, start: "大牟田", end: "宇土", prefs: ["福岡県", "熊本県"], diff: 3, len: 53, auto: true },
  { num: 502, start: "臼杵", end: "竹田", prefs: ["大分県"], diff: 3, len: 52, auto: true },
  { num: 503, start: "高森", end: "日向", prefs: ["熊本県", "宮崎県"], diff: 3, len: 114, auto: true },
  { num: 504, start: "鹿屋", end: "出水", prefs: ["鹿児島県"], diff: 3, len: 135, auto: true },
  { num: 505, start: "本部", end: "名護", prefs: ["沖縄県"], diff: 3, len: 21, auto: true },
  { num: 506, start: "那覇", end: "西原", prefs: ["沖縄県"], diff: 3, len: 12, auto: true },
  { num: 507, start: "糸満", end: "那覇", prefs: ["沖縄県"], diff: 3, len: 25, auto: true }
];
